# scorer/metrics.py
# --------------------------------------------------------------
# Author      : Prakhar Srivastava
# Date        : 2026-06-08
# Description : -> Deterministic, reproducible quality metrics for comparing
#                  an LLM's response against the golden reference answer.
#               -> No LLM calls are made here — this module runs fully offline.
#
#               -> Pipeline position — Stage 2 (Scorer):
#                     Called by scorer/run_scorer.py for every example after
#                     the model response is obtained from inference.py.
#
#               -> Why two metrics?
#                     - BERTScore captures semantic similarity using contextual
#                       embeddings — two sentences that mean the same thing in
#                       different words will still score highly.
#                     - ROUGE-L captures lexical overlap via longest common
#                       subsequence — useful for structured tasks where exact
#                       wording matters (e.g. numbered lists, table formats).
#
#               -> Together they provide a stable, deterministic signal that
#                  anchors the judge LLM's more subjective scoring.
#               -> Running the same inputs twice always returns the same values.
# --------------------------------------------------------------
 
 
# ===============================================================
# Imports
# ---------------------------------------------------------------
# bert_score_fn   : -> bert-score library's main scoring function.
#                   -> Computes Precision, Recall, and F1 between candidate
#                      and reference sentences using BERT embeddings.
#                   -> We use F1 (the harmonic mean) as our single metric value.
# rouge_scorer_lib: -> google-research's rouge_score library.
#                   -> Implements ROUGE-N and ROUGE-L metrics.
#                   -> ROUGE-L uses longest common subsequence (LCS) and
#                      is more robust to word reordering than ROUGE-1/2.
# ===============================================================
from bert_score import score as bert_score_fn
from rouge_score import rouge_scorer as rouge_scorer_lib


# # ===============================================================
# compute_metrics
# ---------------------------------------------------------------
# Computes BERTScore F1 and ROUGE-L between a model response and
# its golden reference answer.
#
# Parameters:
#   response  (str) : The text generated by the LLM under test.
#   reference (str) : The ideal reference response from the golden dataset.
#
# Returns:
#   dict : {
#       "bertscore_f1" : float in [0.0, 1.0] — semantic similarity score.
#                        Higher = more semantically similar to reference.
#       "rougeL"      : float in [0.0, 1.0] — lexical overlap score.
#                        Higher = more words/phrases shared with reference.
#   }
#
# Note on BERTScore computation:
#   bert_score_fn returns tensors (Precision, Recall, F1) for a batch.
#   We pass single-element lists and extract F1[0].item() to get a Python float.
#   lang="en" selects the English-optimized RoBERTa model internally.
#   verbose=False suppresses the progress bar output.
# ===============================================================
def compute_metrics(response: str, reference: str) -> dict:

    # ----------------------------------------------------------
    # BERTScore F1
    # ----------------------------------------------------------
    # Computes semantic similarity using pre-trained BERT embeddings.
    # F1 is the harmonic mean of token-level Precision and Recall.
    # Robust to paraphrasing — "Paris is France's capital" and
    # "The capital of France is Paris" will score very highly.
    # ----------------------------------------------------------
    _, _, F1 = bert_score_fn(
        cands     = [response],
        refs      = [reference],
        lang      = "en",
        verbose   = False,
    )
    bertscore = round(F1[0].item(), 4)

    # ----------------------------------------------------------
    # ROUGE-L
    # ----------------------------------------------------------
    # Measures the longest common subsequence (LCS) between response
    # and reference. use_stemmer=True normalizes word forms (running→run)
    # before comparison, reducing false negatives from minor inflections.
    # ----------------------------------------------------------
    scorer       = rouge_scorer_lib.RougeScorer(["rougeL"], use_stemmer = True)
    rouge_result = scorer.score(reference, response)
    rougeL      = round(rouge_result["rougeL"].fmeasure, 4)

    return{
        "bertscore_f1" : bertscore,
        "rougeL"      : rougeL,
    }